# Generated by Django 6.0.1 on 2026-01-21 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_id', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('category', models.TextField()),
                ('document', models.FileField(blank=True, null=True, upload_to='visitor_documents/')),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.TimeField()),
                ('reason', models.CharField(max_length=200)),
                ('designated_attendee', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='VisitorSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Rescheduled', 'Rescheduled')], default='Pending', max_length=50)),
                ('rescheduled_date', models.DateField(blank=True, null=True)),
                ('rescheduled_time', models.TimeField(blank=True, null=True)),
                ('designated_attendee', models.CharField(blank=True, max_length=100, null=True)),
                ('verification_code', models.CharField(blank=True, max_length=4, null=True)),
                ('in_time', models.TimeField(blank=True, null=True)),
                ('out_time', models.TimeField(blank=True, null=True)),
                ('total_duration', models.DurationField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('visitor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.visitors')),
            ],
        ),
    ]
