# Generated by Django 6.0.1 on 2026-01-21 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_id', models.PositiveIntegerField(unique=True)),
                ('visitor_name', models.CharField(max_length=100)),
                ('visitor_email', models.EmailField(max_length=254)),
                ('category', models.CharField(max_length=50)),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.TimeField()),
                ('reason', models.TextField()),
                ('designated_attendee', models.CharField(max_length=100)),
                ('document', models.FileField(blank=True, null=True, upload_to='visitor_documents/')),
            ],
        ),
        migrations.AlterField(
            model_name='visitorschedule',
            name='visitor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.visitor'),
        ),
        migrations.DeleteModel(
            name='Visitors',
        ),
    ]
